### ISSUE TITLE
Clarification regarding question # 5

### ISSUE THREAD

**Issue by Louis-He** [ZebraEpi/zebra-2019-infosession-py#1]
Is the positive integer *n* mentioned in the problem the same as the one in the formula?
Is that means we should add all the items from 0 till *n*? Something like `$$ e=\sum_{i=0}^{n} \frac{2i+2}{(2i+1)!} $$`?

Thank you.

**Comment by ZebraEpi** [comment]
Yes, it is the same one as in the formula.  The goal is to create an approximate estimate value for the value *e* without having to sum each term up until infinity.
